/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UidRouteImport } from './routes/$uid/route'
import { Route as IndexImport } from './routes/index'
import { Route as LoginRegisterIndexImport } from './routes/login-register/index'
import { Route as UidShopRouteImport } from './routes/$uid/shop/route'
import { Route as UidShoppingCartIndexImport } from './routes/$uid/shopping-cart/index'
import { Route as UidCheckoutIndexImport } from './routes/$uid/checkout/index'
import { Route as UidShopIntelIndexImport } from './routes/$uid/shop/intel/index'
import { Route as UidShopCustomIndexImport } from './routes/$uid/shop/custom/index'
import { Route as UidShopAmdIndexImport } from './routes/$uid/shop/amd/index'

// Create/Update Routes

const UidRouteRoute = UidRouteImport.update({
  id: '/$uid',
  path: '/$uid',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginRegisterIndexRoute = LoginRegisterIndexImport.update({
  id: '/login-register/',
  path: '/login-register/',
  getParentRoute: () => rootRoute,
} as any)

const UidShopRouteRoute = UidShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => UidRouteRoute,
} as any)

const UidShoppingCartIndexRoute = UidShoppingCartIndexImport.update({
  id: '/shopping-cart/',
  path: '/shopping-cart/',
  getParentRoute: () => UidRouteRoute,
} as any)

const UidCheckoutIndexRoute = UidCheckoutIndexImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => UidRouteRoute,
} as any)

const UidShopIntelIndexRoute = UidShopIntelIndexImport.update({
  id: '/intel/',
  path: '/intel/',
  getParentRoute: () => UidShopRouteRoute,
} as any)

const UidShopCustomIndexRoute = UidShopCustomIndexImport.update({
  id: '/custom/',
  path: '/custom/',
  getParentRoute: () => UidShopRouteRoute,
} as any)

const UidShopAmdIndexRoute = UidShopAmdIndexImport.update({
  id: '/amd/',
  path: '/amd/',
  getParentRoute: () => UidShopRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$uid': {
      id: '/$uid'
      path: '/$uid'
      fullPath: '/$uid'
      preLoaderRoute: typeof UidRouteImport
      parentRoute: typeof rootRoute
    }
    '/$uid/shop': {
      id: '/$uid/shop'
      path: '/shop'
      fullPath: '/$uid/shop'
      preLoaderRoute: typeof UidShopRouteImport
      parentRoute: typeof UidRouteImport
    }
    '/login-register/': {
      id: '/login-register/'
      path: '/login-register'
      fullPath: '/login-register'
      preLoaderRoute: typeof LoginRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/$uid/checkout/': {
      id: '/$uid/checkout/'
      path: '/checkout'
      fullPath: '/$uid/checkout'
      preLoaderRoute: typeof UidCheckoutIndexImport
      parentRoute: typeof UidRouteImport
    }
    '/$uid/shopping-cart/': {
      id: '/$uid/shopping-cart/'
      path: '/shopping-cart'
      fullPath: '/$uid/shopping-cart'
      preLoaderRoute: typeof UidShoppingCartIndexImport
      parentRoute: typeof UidRouteImport
    }
    '/$uid/shop/amd/': {
      id: '/$uid/shop/amd/'
      path: '/amd'
      fullPath: '/$uid/shop/amd'
      preLoaderRoute: typeof UidShopAmdIndexImport
      parentRoute: typeof UidShopRouteImport
    }
    '/$uid/shop/custom/': {
      id: '/$uid/shop/custom/'
      path: '/custom'
      fullPath: '/$uid/shop/custom'
      preLoaderRoute: typeof UidShopCustomIndexImport
      parentRoute: typeof UidShopRouteImport
    }
    '/$uid/shop/intel/': {
      id: '/$uid/shop/intel/'
      path: '/intel'
      fullPath: '/$uid/shop/intel'
      preLoaderRoute: typeof UidShopIntelIndexImport
      parentRoute: typeof UidShopRouteImport
    }
  }
}

// Create and export the route tree

interface UidShopRouteRouteChildren {
  UidShopAmdIndexRoute: typeof UidShopAmdIndexRoute
  UidShopCustomIndexRoute: typeof UidShopCustomIndexRoute
  UidShopIntelIndexRoute: typeof UidShopIntelIndexRoute
}

const UidShopRouteRouteChildren: UidShopRouteRouteChildren = {
  UidShopAmdIndexRoute: UidShopAmdIndexRoute,
  UidShopCustomIndexRoute: UidShopCustomIndexRoute,
  UidShopIntelIndexRoute: UidShopIntelIndexRoute,
}

const UidShopRouteRouteWithChildren = UidShopRouteRoute._addFileChildren(
  UidShopRouteRouteChildren,
)

interface UidRouteRouteChildren {
  UidShopRouteRoute: typeof UidShopRouteRouteWithChildren
  UidCheckoutIndexRoute: typeof UidCheckoutIndexRoute
  UidShoppingCartIndexRoute: typeof UidShoppingCartIndexRoute
}

const UidRouteRouteChildren: UidRouteRouteChildren = {
  UidShopRouteRoute: UidShopRouteRouteWithChildren,
  UidCheckoutIndexRoute: UidCheckoutIndexRoute,
  UidShoppingCartIndexRoute: UidShoppingCartIndexRoute,
}

const UidRouteRouteWithChildren = UidRouteRoute._addFileChildren(
  UidRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$uid': typeof UidRouteRouteWithChildren
  '/$uid/shop': typeof UidShopRouteRouteWithChildren
  '/login-register': typeof LoginRegisterIndexRoute
  '/$uid/checkout': typeof UidCheckoutIndexRoute
  '/$uid/shopping-cart': typeof UidShoppingCartIndexRoute
  '/$uid/shop/amd': typeof UidShopAmdIndexRoute
  '/$uid/shop/custom': typeof UidShopCustomIndexRoute
  '/$uid/shop/intel': typeof UidShopIntelIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$uid': typeof UidRouteRouteWithChildren
  '/$uid/shop': typeof UidShopRouteRouteWithChildren
  '/login-register': typeof LoginRegisterIndexRoute
  '/$uid/checkout': typeof UidCheckoutIndexRoute
  '/$uid/shopping-cart': typeof UidShoppingCartIndexRoute
  '/$uid/shop/amd': typeof UidShopAmdIndexRoute
  '/$uid/shop/custom': typeof UidShopCustomIndexRoute
  '/$uid/shop/intel': typeof UidShopIntelIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$uid': typeof UidRouteRouteWithChildren
  '/$uid/shop': typeof UidShopRouteRouteWithChildren
  '/login-register/': typeof LoginRegisterIndexRoute
  '/$uid/checkout/': typeof UidCheckoutIndexRoute
  '/$uid/shopping-cart/': typeof UidShoppingCartIndexRoute
  '/$uid/shop/amd/': typeof UidShopAmdIndexRoute
  '/$uid/shop/custom/': typeof UidShopCustomIndexRoute
  '/$uid/shop/intel/': typeof UidShopIntelIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$uid'
    | '/$uid/shop'
    | '/login-register'
    | '/$uid/checkout'
    | '/$uid/shopping-cart'
    | '/$uid/shop/amd'
    | '/$uid/shop/custom'
    | '/$uid/shop/intel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$uid'
    | '/$uid/shop'
    | '/login-register'
    | '/$uid/checkout'
    | '/$uid/shopping-cart'
    | '/$uid/shop/amd'
    | '/$uid/shop/custom'
    | '/$uid/shop/intel'
  id:
    | '__root__'
    | '/'
    | '/$uid'
    | '/$uid/shop'
    | '/login-register/'
    | '/$uid/checkout/'
    | '/$uid/shopping-cart/'
    | '/$uid/shop/amd/'
    | '/$uid/shop/custom/'
    | '/$uid/shop/intel/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UidRouteRoute: typeof UidRouteRouteWithChildren
  LoginRegisterIndexRoute: typeof LoginRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UidRouteRoute: UidRouteRouteWithChildren,
  LoginRegisterIndexRoute: LoginRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$uid",
        "/login-register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$uid": {
      "filePath": "$uid/route.tsx",
      "children": [
        "/$uid/shop",
        "/$uid/checkout/",
        "/$uid/shopping-cart/"
      ]
    },
    "/$uid/shop": {
      "filePath": "$uid/shop/route.tsx",
      "parent": "/$uid",
      "children": [
        "/$uid/shop/amd/",
        "/$uid/shop/custom/",
        "/$uid/shop/intel/"
      ]
    },
    "/login-register/": {
      "filePath": "login-register/index.tsx"
    },
    "/$uid/checkout/": {
      "filePath": "$uid/checkout/index.tsx",
      "parent": "/$uid"
    },
    "/$uid/shopping-cart/": {
      "filePath": "$uid/shopping-cart/index.tsx",
      "parent": "/$uid"
    },
    "/$uid/shop/amd/": {
      "filePath": "$uid/shop/amd/index.tsx",
      "parent": "/$uid/shop"
    },
    "/$uid/shop/custom/": {
      "filePath": "$uid/shop/custom/index.tsx",
      "parent": "/$uid/shop"
    },
    "/$uid/shop/intel/": {
      "filePath": "$uid/shop/intel/index.tsx",
      "parent": "/$uid/shop"
    }
  }
}
ROUTE_MANIFEST_END */
